"""Remove votes

Revision ID: 175855d4632e
Revises: 
Create Date: 2018-11-19 08:03:01.977293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '175855d4632e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'upvotes')
    op.drop_column('pitches', 'downvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
